# Generated by Django 5.2.7 on 2025-11-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Nama lokasi, e.g., 'Gedung Rektorat UNU Yogyakarta'", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Deskripsi lengkap dan menarik tentang lokasi ini')),
                ('location', models.CharField(default='Yogyakarta', help_text="Kota/Kabupaten lokasi, e.g., 'Sleman, Yogyakarta'", max_length=100)),
                ('published_date', models.DateField(help_text='Tanggal publikasi virtual tour')),
                ('panorama_image', models.ImageField(help_text='Foto 360° dalam format equirectangular (2:1 ratio)', upload_to='panoramas/')),
                ('thumbnail', models.ImageField(help_text='Thumbnail untuk galeri (landscape 16:9 recommended)', upload_to='thumbnails/')),
                ('author', models.CharField(default='Tim Virtual Tour UNU', help_text='Nama pembuat/fotografer', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Tampilkan di virtual tour?')),
                ('is_featured', models.BooleanField(default=False, help_text='Jadikan scene pertama yang muncul?')),
                ('initial_pitch', models.FloatField(default=0, help_text='Sudut vertical awal kamera (-90 to 90)')),
                ('initial_yaw', models.FloatField(default=0, help_text='Sudut horizontal awal kamera (-180 to 180)')),
                ('initial_fov', models.FloatField(default=90, help_text='Field of view awal (50-120)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scene Virtual Tour',
                'verbose_name_plural': 'Scenes Virtual Tour',
                'ordering': ['-is_featured', '-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_type', models.CharField(choices=[('scene', 'Scene Link'), ('info', 'Info Point')], default='scene', max_length=10)),
                ('pitch', models.FloatField(help_text='Sudut vertical (-90 to 90). 0=horizontal, -90=down, 90=up')),
                ('yaw', models.FloatField(help_text='Sudut horizontal (-180 to 180). 0=depan, -90=kiri, 90=kanan')),
                ('text', models.CharField(help_text="Label hotspot, e.g., 'Ke Perpustakaan' atau 'Info Masjid'", max_length=100)),
                ('info_description', models.TextField(blank=True, help_text='Deskripsi detail (hanya untuk type=info)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_scene', models.ForeignKey(help_text='Scene yang memiliki hotspot ini', on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='tour_api.scene')),
                ('to_scene', models.ForeignKey(blank=True, help_text='Scene tujuan (wajib jika type=scene)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='tour_api.scene')),
            ],
            options={
                'verbose_name': 'Hotspot',
                'verbose_name_plural': 'Hotspots',
                'ordering': ['from_scene', 'hotspot_type'],
            },
        ),
    ]
