# Generated by Django 5.2.7 on 2025-12-20 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['building', 'floor', 'order', 'title'], 'verbose_name': 'Scene Virtual Tour', 'verbose_name_plural': 'Scenes Virtual Tour'},
        ),
        migrations.AddField(
            model_name='scene',
            name='building',
            field=models.CharField(default='Gedung Utama', help_text="Nama gedung (e.g., 'Gedung Utama', 'Gedung A', 'Gedung B')", max_length=100),
        ),
        migrations.AddField(
            model_name='scene',
            name='floor',
            field=models.IntegerField(blank=True, help_text='Nomor lantai (1-9). Kosongkan untuk area outdoor/luar gedung.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='scene',
            name='floor_description',
            field=models.CharField(blank=True, help_text="Deskripsi singkat lantai (e.g., 'Ruang Kuliah & Laboratorium')", max_length=200),
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.IntegerField(default=0, help_text='Urutan scene dalam lantai yang sama (untuk sorting). Angka lebih kecil muncul lebih dulu.'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='hotspot_type',
            field=models.CharField(choices=[('scene', 'Scene Navigation'), ('info', 'Info Point'), ('floor', 'Floor Navigation')], default='scene', max_length=10),
        ),
        migrations.AlterField(
            model_name='scene',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Jadikan scene pertama yang muncul (starting point)?'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['building', 'floor'], name='tour_api_sc_buildin_2c555c_idx'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['is_active', 'is_featured'], name='tour_api_sc_is_acti_8b0d49_idx'),
        ),
    ]
