# Generated by Django 5.2.7 on 2026-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0002_alter_scene_options_scene_building_scene_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='building',
            field=models.CharField(choices=[('Gedung Utama', 'Gedung Utama'), ('Gedung MBZ CFS', 'Gedung MBZ CFS')], default='Gedung Utama', help_text='Pilih gedung lokasi scene', max_length=100),
        ),
    ]
