# Generated by Django 5.2.7 on 2026-01-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_api', '0003_alter_scene_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi lengkap dan menarik tentang lokasi ini'),
        ),
    ]
