-- SQL Schema for Tour API (Generated from Django Migrations)
-- You usually DO NOT need to run this manually if you use 'python manage.py migrate'

BEGIN;

--
-- Create model Scene
--
CREATE TABLE "tour_api_scene" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(200) NOT NULL,
    "slug" varchar(50) NOT NULL UNIQUE,
    "panorama_image" varchar(100) NOT NULL,
    "thumbnail" varchar(100) NULL,
    "description" text NOT NULL,
    "location" varchar(200) NULL,
    "initial_pitch" numeric(5, 2) NOT NULL,
    "initial_yaw" numeric(5, 2) NOT NULL,
    "initial_hfov" numeric(5, 2) NOT NULL,
    "auto_rotate_speed" numeric(4, 1) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "is_featured" boolean NOT NULL
);

--
-- Create model Hotspot
--
CREATE TABLE "tour_api_hotspot" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "text" varchar(100) NOT NULL,
    "pitch" numeric(5, 2) NOT NULL,
    "yaw" numeric(5, 2) NOT NULL,
    "type" varchar(20) NOT NULL,
    "scene_id" bigint NOT NULL REFERENCES "tour_api_scene" ("id") DEFERRABLE INITIALLY DEFERRED,
    "to_scene_id" bigint NULL REFERENCES "tour_api_scene" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "tour_api_hotspot_scene_id_key" ON "tour_api_hotspot" ("scene_id");
CREATE INDEX "tour_api_hotspot_to_scene_id_key" ON "tour_api_hotspot" ("to_scene_id");
CREATE INDEX "tour_api_scene_slug_like" ON "tour_api_scene" ("slug" varchar_pattern_ops);

COMMIT;
